apiVersion: v1
kind: Service
metadata:
  name: oncosurvivalui-svc # Name of Service
  annotations:
    cloud.google.com/neg: '{"ingress": true}' # Creates a NEG after an Ingress is created
spec: # Service's specification
  type: ClusterIP
  selector:
    app: oncosurvivalui # Selects Pods labelled app: oncovision
  ports:
  - name: http
    port: 80 # Service's port
    protocol: TCP
    targetPort: 8501
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oncosurvivalui-ing
spec:
  defaultBackend:
    service:
      name: oncosurvivalui-svc # Name of the Service targeted by the Ingress
      port:
        number: 80 # Should match the port used by the Service
