name: oncovision backend CI job
on:
  push:
    branches:
      - '*'
    
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check files
        run: |
          set -x
          ls -ltra
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: europe-west3-docker.pkg.dev
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: europe-west3-docker.pkg.dev/solution-kit-11/oncovision/oncobackend:${{ github.ref_name }}
          build-args: |
            "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
            
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./survival_ui
          push: true
          tags: europe-west3-docker.pkg.dev/solution-kit-11/oncovision/oncosurvivalui:${{ github.ref_name }}

  deploy-image:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check the files
        run: |
          set -x
          ls -ltra
      
      - name: Update manifest with new image
        run: |
          set -x
          sed -i 's/oncobackend:latest/oncobackend:${{ github.ref_name }}/g' ./.kubernetes/workload.yaml
          cat ./.kubernetes/workload.yaml
          sed -i 's/oncosurvivalui:latest/oncosurvivalui:${{ github.ref_name }}/g' ./.kubernetes/workloadui.yaml
          cat ./.kubernetes/workloadui.yaml
      
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: 'get-gke-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'oncovision'
          location: 'europe-west3'

      - name: 'apply workload'
        run: |
          kubectl apply -f ./.kubernetes/workload.yaml
          kubectl apply -f ./.kubernetes/workloadui.yaml

      - name: 'create service'
        run: |
          kubectl apply -f ./.kubernetes/service.yaml
          kubectl apply -f ./.kubernetes/serviceui.yaml
      
      - name: "Roll out"
        run: |
          kubectl rollout restart deployment/oncobackend
          kubectl rollout restart deployment/oncosurvivalui
